name: docs
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_needs

      - name: Build docs
        run: |
          sphinx-build -b html docs docs/_build/html
          # If using needexport or needs_build_json, ensure your needs.json is in docs/_build/html or docs/_build/json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repoA-docs
          path: docs/_build
